### ISSUE TITLE
[ Bug ]: 在 discusskit 里面上传 cover 的时候，体验有点奇怪

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/image-bin#101]
# 🐛 Bug Report

## 详细描述

https://github.com/blocklet/image-bin/assets/12446758/d4c6f0dc-e14e-4442-a2dd-b42085f2826c

期望的上传完成，点击 done 就结束了，结果这个弹窗还在这。

**Comment by NateRobinson** [comment]
https://github.com/blocklet/image-bin/issues/94

**Comment by FireTable** [comment]
fixed
