### ISSUE TITLE
[ Bug ]: uploaded 出现破图

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#109]
# 🐛 Bug Report

## 详细描述

给出URL，让其下载后上载，看起来一切正常，但imagebin 关闭后为破图。 查看uploaded 也是破的 

## 截图或报错信息(可选)

<img width="774" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/6af79d71-2616-47cf-b3a5-9578913171b1">

**Comment by FireTable** [comment]
复现出来了，与 copy url 的路径有关
```
https://images.unsplash.com/photo-1695040813576-5aa20636688c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2787&q=80
```

这张图片因为存在 rb-4.0.3 这一类参数，被错误截取了当做扩展名了，我修复下

**Comment by FireTable** [comment]
done and verified in staging
![image](https://github.com/blocklet/image-bin/assets/24667209/12d91a01-77d6-4b13-aed3-28a427f5b086)
