### ISSUE TITLE
[ Bug ]: Connection with Companion failed 

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#113]
# 🐛 Bug Report

## 详细描述

莫名就出现了这个错误，过去还能用的。 

<img width="857" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/92c99f99-96b4-4541-9690-c4278aa2c41a">

**Comment by FireTable** [comment]
调整热更新 Unsplash Key 导致的问题 @mave99a 
新版做了一版修复，需要更新 Image Bin

**Comment by FireTable** [comment]
fixed and verified in staging
![image](https://github.com/blocklet/image-bin/assets/24667209/da597d45-074c-468d-b5d9-b642d5f5f585)
