### ISSUE TITLE
[ Discuss ] 应该判断 ai 是否可用，不可用应该禁用或隐藏 ai 入口

### ISSUE THREAD

**Issue by li-yechao** [blocklet/image-bin#114]
## Discuss topic

<img width="890" alt="image" src="https://github.com/blocklet/image-bin/assets/21697340/ae548714-0c54-4c04-9e3d-1014b117f419">

判断方式：通过接口调用 ai-kit 的 status 接口

```ts
const res = await call({
  name: 'ai-kit',
  path: '/api/v1/sdk/status',
  data: {}
})

res // { available: boolean }
```

**Comment by FireTable** [comment]
done and verified in staging
![image](https://github.com/blocklet/image-bin/assets/24667209/35901a6e-c81d-4c52-b310-ebf1d65f8579)
