### ISSUE TITLE
[ Bug ]: 中文的图片上传失败，改为英文就可以了

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#121]
# 🐛 Bug Report

## 截图或报错信息(可选)

独上江楼思渺然，_月光如水水如天。_同来望月人何处？_风景依稀似去年.png

<img width="765" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/917258e4-c7b8-45e3-ba03-08be9f7bcd76">

**Comment by FireTable** [comment]
比较隐秘的问题, 发现是中文文件名 stringify 后，默认 UTF-8，但是上传底层 XML 只能接收 ISO-8859-1 编码的字符

**Comment by FireTable** [comment]
已经让其它  Blocklet 升级
image bin verified and close

![image](https://github.com/blocklet/image-bin/assets/24667209/8dd996e4-d847-4dc6-a5a6-6e06fe1dcb05)
