### ISSUE TITLE
[ Bug ][@blocklet/uploader]: 上传一个空文件(size 为 0)的时候,上传会失败

### ISSUE THREAD

**Issue by skypesky** [blocklet/image-bin#124]
# 🐛 Bug Report

## 截图或报错信息(可选)

![image](https://github.com/blocklet/image-bin/assets/33124160/77668c88-dc6f-40db-a180-4b4d75f2bb75)

**Comment by FireTable** [comment]
verified and fixed in staging

![image](https://github.com/blocklet/image-bin/assets/24667209/b3dc0bc5-4730-4dc3-aa64-bd18fccf8b4d)
