### ISSUE TITLE
[ Bug ]:我个人站点，最新 imagebin， load from uploaded 不正常

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#127]
# 🐛 Bug Report

## 详细描述

我个人站点，最新 imagebin， load from uploaded 不正常。

## 复现这个 bug

1、一直处于loading 的状态
2、也无法退出这个状态 （cancel 没有用，refresh整个页面可以）

## 截图或报错信息(可选)

<img width="1297" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/126b18a8-6589-43a3-bfd9-e229eee5f4f4">

**Comment by FireTable** [comment]
验证已恢复正常

![image](https://github.com/blocklet/image-bin/assets/24667209/cc82a933-6bde-4a11-89de-950d5d2d94bd)
