### ISSUE TITLE
[ Feature ] 希望能支持打开 Uploaded 列表时能在第一张图的位置加一个上传按钮

### ISSUE THREAD

**Issue by li-yechao** [blocklet/image-bin#134]
## Target / Intent / Why you want this Feature
<img width="1090" alt="image" src="https://github.com/blocklet/image-bin/assets/21697340/2875cc70-2ae6-4551-8424-5050853ea3a0">

如图，这样我们在某些需要支持选择内置图片和自定义上传图片的场景中就可以直接复用 upload dialog，而不用每个应用自己去开发

**Comment by FireTable** [comment]
done
