### ISSUE TITLE
[ Bug ]: 嵌入的 imagebin 里输入区域均不能输入

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#140]
# 🐛 Bug Report

## 详细描述

在一些嵌入使用imagebin 的地方，需要输入的地方都不能输入， 无法focus获得输入caret。 

这个例子是在Ai Studio 的 project setting里的图标的地方发现的。 

## 截图或报错信息(可选)

<img width="840" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/43019d76-a103-4fb1-a628-0608bb655a5a">

**Comment by FireTable** [comment]
好像跟 Aistudio 的遮罩有关，我去帮忙调整下，或者让 uploader 的遮罩更加"好"

**Comment by leermao** [comment]
已经修复

**Comment by FireTable** [comment]
验证 staging 正常了
![image](https://github.com/blocklet/image-bin/assets/24667209/f521e219-9f93-42fb-b3a6-9f2c69090f4e)
