### ISSUE TITLE
[ Bug ]: upload 了两个 SVG，无法插入 discuss kit 的post里

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#142]
# 🐛 Bug Report

## 详细描述

 upload 了两个 SVG，无法插入 discuss kit 的post里。 当然也有可能是discuss kit 的editor 问题。

**Comment by FireTable** [comment]
<img width="732" alt="image" src="https://github.com/blocklet/image-bin/assets/24667209/ec6bc5b3-bb3e-4324-bf7e-810b448db644">

测试发现确实是有问题, 有的 svg 无法上传（国旗的）, 我看看什么问题

**Comment by FireTable** [comment]
![image](https://github.com/blocklet/image-bin/assets/24667209/f0549f54-f7f8-487b-b794-4ddfc26cd7ba)

discuss kit 做了修复，有空可以升级后，帮忙看看 @mave99a
