### ISSUE TITLE
[ Bug ]: Image Bin 打包大小异常

### ISSUE THREAD

**Issue by FireTable** [blocklet/image-bin#144]
# 🐛 Bug Report

## 详细描述

@LancelotLewis  发现 Image Bin 从以前改版前 26MB => 55MB
下载代码包查看后, 发现 @blocklet/uploader 里面，有个 @mui 的依赖大老虎

看上去是重复打包了文件, 可能需要 resolutions 处理一下
减少每个应用 Image Bin 的体积

![image](https://github.com/blocklet/image-bin/assets/24667209/0efc1202-ea02-4f7b-9543-87faf2d22cd5)

**Comment by FireTable** [comment]
这个问题目前没有找到解决办法，打包流程如下
1. image-bin 依赖 @blocklet/uploader, 在 pnpm 中通过 ^workspace 链接
2. 在 pnpm 的时候, 尽管 .npmrc 要求依赖提升到根目录，但是 @blocklet/uploader 依然保留了 @mui 的包
    <img width="301" alt="image" src="https://github.com/blocklet/image-bin/assets/24667209/fdfd8e33-a14d-4d98-b274-564cb55a1cf1">
3. 因为 @blocklet/uploader 包含前后端，而 image bin 在打包的时候会把后端依赖也打包，所以 image bin zip 包包含了@mui

**Comment by LancelotLewis** [comment]
新版已经使用 ncc 来进行打包，整个 image-bin 的大小已经缩减到 4M
