### ISSUE TITLE
[ Bug ]: 浏览 images 时自动下载了大量的图片

### ISSUE THREAD

**Issue by li-yechao** [blocklet/image-bin#146]
# 🐛 Bug Report

## 详细描述

https://github.com/blocklet/image-bin/assets/21697340/02616812-586b-4676-88f4-fe74066b65a5

**Comment by FireTable** [comment]
感觉是备份还原带来的问题, 我看看

**Comment by FireTable** [comment]
<img width="1057" alt="image" src="https://github.com/blocklet/image-bin/assets/24667209/054ee75b-3802-43ba-9739-f2fe384a90e8">

这些图片都是没有后缀名的图片格式

// 最近的一张是 7 月 31 号，此时还是有 下载 bug 的状态
![image](https://github.com/blocklet/image-bin/assets/24667209/9932b39b-496a-4f3f-9025-6b4d41c87aba)

属于脏数据，我处理一下

**Comment by FireTable** [comment]
@li-yechao 有空可以翻一下，看看会不会自动下载了

**Comment by li-yechao** [comment]
没有复现了
