### ISSUE TITLE
[ Bug ]: 必须点以下image bin 才能接受 paste

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#149]
从这里：
<img width="808" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/d6c7b9df-bdd8-4d20-8495-df83af1bd63e">

点一下打开image bin：
<img width="877" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/e32f3de2-f1ac-4d4b-9b5c-a07cbdb098bf">

然后试图 paste，没有用。 

需要click 一下image bin 的任何位置，才可以paste。

**Comment by mave99a** [comment]
用户不可能知道需要click 一下

**Comment by FireTable** [comment]
fixed and verified
