### ISSUE TITLE
这个可以考虑改名为 Media-kit

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#16]
这个可以考虑改名为 Media-kit, 和Publish-kit, Discuss-Kit 配套。 

叫media 意味着，以后除了图片，其他媒体也能处理，例如视频、文件等。

**Comment by FireTable** [comment]
done，发现了一些潜在的问题
https://test.store.blocklet.dev/blocklets/z8ia1mAXo8ZE7ytGF36L5uBf9kD2kenhqFGp9
https://store.blocklet.dev/blocklets/z8ia1mAXo8ZE7ytGF36L5uBf9kD2kenhqFGp9

related: 
https://github.com/ArcBlock/blocklet-server/issues/8277
https://github.com/ArcBlock/blocklet-server/issues/8276
