### ISSUE TITLE
[ Bug ]: ALL 中没有加载更多图片

### ISSUE THREAD

**Issue by li-yechao** [blocklet/image-bin#168]
# 🐛 Bug Report

## 截图或报错信息(可选)

https://github.com/blocklet/image-bin/assets/21697340/d2c0c22b-f008-4bdd-af0c-4d054689f71d

**Comment by FireTable** [comment]
我优先看看这个问题

**Comment by FireTable** [comment]
与之前做资源型组件去掉了 wrapperRef 有关
<img width="878" alt="image" src="https://github.com/blocklet/image-bin/assets/24667209/1be528a7-45b6-48e9-be25-1e6620ca2d7a">

**Comment by FireTable** [comment]
fixed and updated and verified

<img width="1193" alt="image" src="https://github.com/blocklet/image-bin/assets/24667209/bf92e1d0-635c-4a9b-93d9-ac3f9da604be">
