### ISSUE TITLE
[ Discuss ] 透明图片 preview 的时候底部可以采用常见的格子图案， 而我们目前黑色导致一些黑色的图片完全看不见

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#170]
## Discuss topic

透明图片 preview 的时候底部可以采用常见的格子图案， 而我们目前黑色导致一些黑色的图片完全看不见
<img width="817" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/cab44de7-234b-453e-9868-2316d5eb9214">

更好应该这样： 
<img width="382" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/170e1cd2-ffb9-4c67-9354-c4cc33d8241d">

**Comment by FireTable** [comment]
done
