### ISSUE TITLE
[ Discuss ] 应当允许video

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#174]
## Discuss topic

我们反正decentralized，存储都用户自己的，应该允许upload video，多大的都可以

现在discuss kit 里不允许我uplaod video，不知道是 image bin限制，还是discuss kit 的限制

**Comment by FireTable** [comment]
image bin 的上传是支持 upload video 的
对于 image bin 中，通过 prefs 来进行配置，就可以支持上传

而对于 uploader  组件，discuss kit 是可以上传 video 的，不需要在 image bin 配置（没有做限制）
具体需要看 discuss kit 的实现，也就是需要 discuss kit 支持 video

下周我跟 wangqi 聊一下，如果不难我来做个支持

**Comment by donotlb** [comment]
搜b一圈，lexical editor 似乎没有直接可用的 video plugin，有人提过[ video 支持的 issue](https://github.com/facebook/lexical/issues/1166), 但官方在支持了 youtube video 后就把 issue close 了, 我们想要的其实是支持播放自己 host 的 video

和 @FireTable 讨论了下, 目前看需要自己实现一个 plugin，计划用 video.js 或者简单的基于 html5 video tag 弄一个

**Comment by FireTable** [comment]
done
