### ISSUE TITLE
[ Discuss ] 需要支持自动压缩图片

### ISSUE THREAD

**Issue by li-yechao** [blocklet/image-bin#196]
## Discuss topic

image-bin 可以设置最大上传文件大小，如果 AI 生成的图片大于最大上传文件大小，将会报错，能否在前端自动压缩到限制大小内后上传呢？

**Comment by FireTable** [comment]
我觉得保留原图是合适的，因为我们server支持压缩图片
先压缩再上传就救不回来了

现在 image bin 默认是 30MB ，对于 AIGC 图片其实是够用的？
<img width="475" alt="image" src="https://github.com/blocklet/image-bin/assets/24667209/78993d67-518e-4ba0-b188-89be9535cbc8">

不过可能上传 video 不够用，先看看情况

**Comment by mave99a** [comment]
我们去中心化的业务，可以默认允许比较大，甚至无限。

**Comment by FireTable** [comment]
> 我们去中心化的业务，可以默认允许比较大，甚至无限。

可能早上 yechao 改的需要再调整，目前是限制了使用 Image Bin 限制的大小
https://github.com/blocklet/image-bin/pull/195

或者把默认 env 先设为 500MB 也可以，因为我们现在 server 的 nginx 限定的就是 500 MB

**Comment by FireTable** [comment]
加上限制之后，DID Spaces 更新 uploader 后受到了影响
rollback 了之前限制的逻辑
