### ISSUE TITLE
[ Bug ]: 有的时候期下载的文件名是有意义的，而不是一串随机字符

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/image-bin#225]
# 🐛 Bug Report

## 详细描述

这个页面的 https://www.arcblock.io/docs/arcblock/en/arcblock-media-kit 的 Download 下载下来的 zip 文件叫：a997fccf2f70927fe2dc449b37fb5250.zip

其实在 Media Kit 它叫：arcblock-mediakit.zip
<img width="350" alt="截屏2024-02-28 下午2 31 52" src="https://github.com/blocklet/image-bin/assets/12446758/681eaa7a-272a-4d97-8976-da0c1fead552">

如果用户下载下来叫 arcblock-mediakit.zip ，这个名字对用户更有意义和辨识度。

**Comment by FireTable** [comment]
fixed and verified in staging

# 下载 zip，带名称
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/media/uploads/a6df8514cdf637a1b0ee25e3bdea15fc.zip?filename=planet-of-paid-knowledge-1.0.3.zip

# 浏览器浏览 zip (触发下载, hash
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/media/uploads/a6df8514cdf637a1b0ee25e3bdea15fc.zip

# 下载 png
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/media/uploads/e96f9dfd58a2d6de9e2581a9a8b92c47.png?filename=%E4%BA%94%E7%BA%A2%E8%A0%A2%E8%A0%A2.png

# 浏览器浏览 png 不下载
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/media/uploads/e96f9dfd58a2d6de9e2581a9a8b92c47.png
