### ISSUE TITLE
一张 34 kb 的 png 图上传之后变成了 jpeg 格式，并且大小变成了 300 多 kb

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/image-bin#23]
这是原图尺寸
![截屏2023-01-05 14 57 13](https://user-images.githubusercontent.com/12446758/210720426-25c1693f-aa18-4c90-89fb-8b1076fd1382.png)

上传了 image bin 之后：
![截屏2023-01-05 14 58 31](https://user-images.githubusercontent.com/12446758/210720489-bd15f4bc-b27c-4c82-9d5c-433cccfe24e4.png)

https://image-bin-gp9-18-180-145-193.ip.abtnet.io/uploads/1672901762844-W7CNIE6B3av0F_6zR5uURKQB.jpeg 

格式已经变了。

**Comment by wangshijun** [comment]
是不是现有的上传里面有图片的 resize 导致的？你的需求是什么？这种 resize 导致了什么问题？

**Comment by NateRobinson** [comment]
我的需求
- 图片尺寸不应该变化，辛苦的把图片压缩到 30 kb 左右，结果一上传，变的比压缩前还大
- 图片格式不应该变化，png 到 jpeg 的话，透明通道就丢了

**Comment by li-yechao** [comment]
这个问题是因为 Uppload 的配置导致的，使用以下方法可以快速 fix

```ts
const uppload = new Uppload({
  compressionFromMimes: [] // 加入这一行配置可以支持上传原图
});
```

**Comment by li-yechao** [comment]
fixed in #24

**Comment by NateRobinson** [comment]
验证已修复。
