### ISSUE TITLE
[ Bug ]: 期望图片列表可以有更好的预览方式

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/image-bin#234]
# 🐛 Bug Report

## 详细描述

现在在 image bin 后台看上传的图片，不点开很难看全，几乎都被裁剪了
![截屏2024-03-13 22 42 54](https://github.com/blocklet/image-bin/assets/12446758/5266d1ca-b6b4-49b5-aa23-1f8c0f225cc6)

object-fit 改成 none 似乎可以？ 现在是 cover。

**Comment by mave99a** [comment]
masonary 瀑布流布局？

**Comment by FireTable** [comment]
mui masonary 之前试过，但是没办法解决刷新之后图片跳动的问题
后面再尝试一下

**Comment by FireTable** [comment]
在新版的 Media Kit 已经调整了 objectFit, Team DAO 可以体验
本周内会发布 Prod Store

mui masonary 另外建了 issue https://github.com/blocklet/image-bin/issues/247

<img width="1309" alt="image" src="https://github.com/blocklet/image-bin/assets/24667209/85262ab5-60f3-4632-9fd9-2331402ab1ac">
