### ISSUE TITLE
新建 folder 但还没上传任何图片之后没有显眼的上传按钮

### ISSUE THREAD

**Issue by wangshijun** [blocklet/image-bin#243]
![Screenshot 2024-04-27 at 16 19 23](https://github.com/blocklet/image-bin/assets/719985/d6f48c6c-51b5-4438-9bd9-e1cc69e6a7b0)

**Comment by wangshijun** [comment]
比如，上面左侧这个按钮，在图片为空的时候并没有展示

**Comment by FireTable** [comment]
fixed 
<img width="1222" alt="image" src="https://github.com/blocklet/image-bin/assets/24667209/5b2ca1f2-709e-4c9a-bf0f-ba46a84ac56a">
