### ISSUE TITLE
打开 image bin url 之后会出现自动下载文件的弹窗

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/image-bin#44]
![截屏2023-07-18 20 37 25](https://github.com/blocklet/image-bin/assets/12446758/de0fb0f9-1e9f-4258-b690-17cb78d6bfc5)
![截屏2023-07-18 21 14 52](https://github.com/blocklet/image-bin/assets/12446758/2fd42775-8baa-49e8-9fb5-5c145c31e9ec)

**Comment by wangshijun** [comment]
@NateRobinson 这个问题我没有复现，等你回来我看下你那边的现场

**Comment by li-yechao** [comment]
https://github.com/blocklet/image-bin/assets/21697340/0708f848-8fec-45d2-881b-1f8992462fc4


我这边也是一样，并且点击 upload 没反应

**Comment by FireTable** [comment]
目前 image bin 不会再有这个问题了, fixed
