### ISSUE TITLE
Aistro 里面好几个 blocklet 都用到了 image-bin 服务，期望 image-bin 可以实现自动的分组功能

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/image-bin#55]
![截屏2023-08-03 21 52 40](https://github.com/blocklet/image-bin/assets/12446758/55b0e3da-c5b8-4d3e-baa6-2783dd0a52ec)

现在 aistro 里面的图片资源都混在了一起
- 有来自 pageskit 的
- 有为了 tweet token 活动上传的
- 有来自 aistro 客户端的用户头像

 目前比较混乱，也不太好管理，是否有必要加上一个自动的 group 能力，pageskit 的都自动聚合到 pageskit 下面，aistro 的用户头像都自动聚合到头像分组下面。

**Comment by wangshijun** [comment]
这个想法不错，和可组合性非常贴合，类似的实践在 discuss-kit 里面也实现过，比如：

- team 下面的 vote + discuss-kit
- store 下面的 blocklet + discuss-kit

**Comment by wangshijun** [comment]
实现方案：自动按 componentDid 来分组（component name 为组名），但是可以挪动分组

**Comment by wangshijun** [comment]
@li-yechao aistro 的上传是如何完成的？参考 pages-kit 的 pr 去改动即可
