### ISSUE TITLE
使用文件 md5 作为文件名后，多次上传同一个文件，然后删除其中一个，所有上传的链接都会失效

### ISSUE THREAD

**Issue by li-yechao** [blocklet/image-bin#57]
使用不同的 `x-component-did` 上传同一个图片到不同分组下面，删除其中一个文件，然后其它分组下面的链接 404

**Comment by wangshijun** [comment]
确实是个问题，只删除 db 记录，不删除磁盘文件

**Comment by li-yechao** [comment]
> 确实是个问题，可以考虑只删除 db 记录，不删除磁盘文件？或者增加计数？

可以考虑在删除文件时查询一下引用数量（不增加计数字段，避免维护冗余字段），没有引用再删除

**Comment by FireTable** [comment]
fixed
