### ISSUE TITLE
imagebin的奇怪问题（在我的个人站点上）

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#60]
默认管理这样：
<img width="1417" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/8ef0c172-86e4-4457-840e-b4fc21beebdc">

但只要click 一个 tab：

<img width="1421" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/d66891b8-bff0-453b-b004-a14b2e00310b">

tab 就消失了。 

upload 后也找不到哪里去了。 

在imagebin里看不见 discuss kit 里的任何upload。 

可能和这个问题也相关：
- https://github.com/blocklet/pages-kit/issues/529

**Comment by wangshijun** [comment]
> tab 就消失了。

我登陆到你的站点后台，未能复现

> upload 后也找不到哪里去了。

我验证了上传，直接通过 image-bin 管理界面上传的会出现在 image-bin tab 和 all tab 下面

> 在imagebin里看不见 discuss kit 里的任何upload。

discuss-kit 目前的上传确实不在 image-bin 里面，有 issue https://github.com/blocklet/discuss-kit/issues/1091

**Comment by FireTable** [comment]
这个 issue 已经处理挺久了，目前已经没有上面 comment 的问题
