### ISSUE TITLE
[Bug]: copy url 按钮到剪切板的值不正确

### ISSUE THREAD

**Issue by FireTable** [blocklet/image-bin#63]
Image Bin
0.9.17

用户反馈的问题（验证确实有问题），点击 copy url，拿到的是 
ce68c89339aaeba0698473534a932842.png

正常应该是
https://www.luckwheel.xyz/image-bin/uploads/ce68c89339aaeba0698473534a932842.png

![image](https://github.com/blocklet/image-bin/assets/24667209/bf0e6321-84d6-4c6c-8b1c-0c9737a1a1c6)

**Comment by wangshijun** [comment]
fixed in v0.9.18
