### ISSUE TITLE
uploaded tab 每次都很慢，而且好像图片大，没有cache

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#65]
参考视频：

https://github.com/blocklet/image-bin/assets/41923/e970e242-320f-427a-8d97-59e92b2ccbdc

**Comment by wangshijun** [comment]
@li-yechao 貌似请求的是原图？

**Comment by wangshijun** [comment]
@li-yechao @donotlb 这个最好在应用侧做下适配：

- 后端返回的是原图的地址
- 前端根据自己展示的大小，拼接裁剪参数
- 用户选择的时候，使用原图（这个未来需要继续优化）

**Comment by FireTable** [comment]
PagesKit 使用的通用上传组件已经默认 imageFilter 并且 HIT cache
![image](https://github.com/blocklet/image-bin/assets/24667209/7d009f95-e32a-47d3-8584-5d085a36e51c)

![image](https://github.com/blocklet/image-bin/assets/24667209/a69a72c0-38b4-47f4-8305-9ba9933f937c)
