### ISSUE TITLE
[ Bug ]: serverless pool的新instance，任何image upload 都出错

### ISSUE THREAD

**Issue by mave99a** [blocklet/image-bin#85]
# 🐛 Bug Report

## 截图或报错信息(可选)

<img width="945" alt="image" src="https://github.com/blocklet/image-bin/assets/41923/22a37a27-add5-4ac3-8dfe-f99e1bea183d">

**Comment by mave99a** [comment]
感觉是老 iamgebin， 不确定那里的问题。 过去没有问题的。

**Comment by FireTable** [comment]
我看看什么回事，有点诡异

**Comment by FireTable** [comment]
在 staging launcher 复现出来了，跟 pagesKit 默认使用 test store 的 image bin 有关
我马上做个修复

<img width="304" alt="image" src="https://github.com/blocklet/image-bin/assets/24667209/beb85ae6-5ec0-488a-b5f7-49a2724f8ea7">

**Comment by FireTable** [comment]
fixed and verified，新安装的已经没问题
@mave99a 老安装的版本, 因为 image-bin 已经是 test store 的，需要移除 pages kit + image bin，重新安装 prod store 的 pages kit

<img width="1117" alt="image" src="https://github.com/blocklet/image-bin/assets/24667209/8d91838d-5b30-43ca-af7f-87327b694fb4">

**Comment by FireTable** [comment]
fixed 很久了
