### ISSUE TITLE
[ Bug ]: @blocklet/uploader 文案上需要支持 i18n

### ISSUE THREAD

**Issue by skypesky** [blocklet/image-bin#88]
# 🐛 Bug Report

## 截图或报错信息(可选)

<img width="1897" alt="image" src="https://github.com/blocklet/image-bin/assets/33124160/2344bdc1-0d68-4870-8685-9918da2fe47d">

**Comment by skypesky** [comment]
![image](https://github.com/blocklet/image-bin/assets/33124160/c35f291f-7061-46d7-8f2a-75385feedeb8)

![image](https://github.com/blocklet/image-bin/assets/33124160/eaa3a91d-8ea4-4fc0-b715-a2e9138a6381)

@FireTable i18n 还需要点小改动

**Comment by FireTable** [comment]
包含 image bin + uploader 的 i18n 均已更新
