### ISSUE TITLE
无法上传大图，会一直 loading

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/image-bin#9]
![WechatIMG243](https://user-images.githubusercontent.com/12446758/189466725-216c61ff-b945-46c0-b8be-88b804c66563.jpeg)

尝试上传一个 4M 的图片，就会一直 loading

**Comment by wangshijun** [comment]
这是因为自动限制了 1MB 的大小

**Comment by wangshijun** [comment]
什么场景下需要上传这么大的文件？

**Comment by wangshijun** [comment]
可以做成跟 store 那样可以配置的

**Comment by NateRobinson** [comment]
这是一个用户反馈的，如果我们不支持 1M 以上的图片，可以给用户来个提示？或者超过 size 的直接不让 upload？
