### ISSUE TITLE
[ Bug ]: 上传文件和文件夹时，发送了多次 POST 请求，即上传了多次同样的文件上来，导致立即删除文件的时候，DID Spaces 文件又被上传了一次。

### ISSUE THREAD

**Issue by skypesky** [blocklet/image-bin#91]
# 🐛 Bug Report

## 截图或报错信息(可选)

- [ ] access.log被上传了2次.mp4,前后修改时间不一致，左下角请求数飙升

https://github.com/blocklet/image-bin/assets/33124160/862d4acc-e2f6-41bc-a7d4-efa9bb31e6ed

**Comment by FireTable** [comment]
fixed and polish DID spaces code
