### ISSUE TITLE
[ Bug Bash ]: 2023-09-18 通用上传组件相关 blocklet  回归测试

### ISSUE THREAD

**Issue by FireTable** [blocklet/image-bin#94]
## 背景介绍
最近我们新增了通用上传组件 @blocklet/uploader，且替换了部分 Blocklet 的上传功能
1. Image Bin 替换 uppload 组件，并且支持更好的组合上传功能
2. Pages Kit 替换 uppload 组件， 并且复用 Image Bin 上传功能
3. Discuss Kit 替换 uppload 组件，并且兼容 Image Bin，使其更加统一

目前这些 Blocklet 都已经上传到 test store，需要做一次 bugbash 来保证功能正常，然后发布到正式环境

* 所有遇到的问题，一律提交到 Image Bin issues 中，我来做分拣

## 前置准备

除了 Nate 外
1. 准备一些图片与视频，与实时截图的软件（支持 copy paste 到 uploader）
2. 前往 https://node-dev-1.arcblock.io/admin/blocklets/zNKYnJaQwg8xy2vcAKP1XisnfSzVxBUp7wBK/components 领取 admin passport
3. 从 dashboard 选择需要测试的 blocklet

### 仿新用户测试 @NateRobinson 
https://launcher.staging.arcblock.io/app/?paymentMethod=1en6L0z8GrIW6mYC
- [ ] 安装新版的 Pages Kit，无法移除 Image Bin
- [ ] 安装新版的 Discuss Kit，会额外安装 Image Bin，且无法移除 Image Bin
- [ ] 新用户安装 Image Bin，未配置 UNSPLASH_KEY 不出现 unsplash 插件
       - https://unsplash.com/developers 可以在这里申请
- [ ] 新用户安装 Image Bin，未组合 AI Kit，不出现 AI 插件

### Image Bin  @leermao  @skypesky 
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/image-bin/admin/images
- [ ] 在 /admin/images 点击右上角触发图片上传 dialog
- [ ] 选择多张图片（包括单张）进行上传
- [ ] 使用远程图片上传（URL、Unsplash）
- [ ] 使用 AI 生成图片
- [ ] 拖拽文件到组件 dialog 进行上传
- [ ] 重复文件上传，速度会非常快
- [ ] 选择视频进行上传
- [ ] 在白名单范围外的文件无法上传
      ![image](https://github.com/blocklet/image-bin/assets/24667209/806f8782-4952-492a-99fd-68e03e1b762b)
- [ ] 超过上传大小限制: 30MB 的无法上传
      ![image](https://github.com/blocklet/image-bin/assets/24667209/d6c366ce-bf9f-4c5a-afd3-df676fddf175)
- [ ] 在 Image Bin 上传的图片，可以进行删除
- [ ] 竖排长图 hover 鼠标会进行图片滚动预览
- [ ] 切换顶部的 Tab 来筛选不同 Blocklet 上传的图片，其它 Blocklet 的图片无法删除

### Pages Kit @leermao @donotlb
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/admin/maker
- [ ] 选择单张图片进行上传，无法选择多张
- [ ] 选择视频进行上传
- [ ] 拖拽文件到组件 dialog 进行上传
- [ ] 使用 AI 生成图片
- [ ] 上传的内容可以超过 30MB 的限制大小
- [ ] 上传的内容可以在 Image Bin 查到
- [ ] 使用 Uploaded 选择已经上传的图片

### Discuss Kit @donotlb @skypesky 
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/did-comments/?locale=zh
- [ ] editor 输入 /image ，可以打开 uploader
- [ ] uploader 中可以选择多张图片上传
- [ ] uploader 中使用 AI 生成图片
- [ ] 用远程图片上传（URL、Unsplash）
- [ ] editor 拖拽多张图片触发静默上传
- [ ] 上传的内容可以超过 30MB 的限制大小
- [ ] 上传的内容可以在 Image Bin 查到
- [ ] 使用 Uploaded 选择已经上传的图片
- [ ] 在 Blog 中（/blog），封面图只能上传一张图片

### Aistro @NateRobinson 
- [ ] Aistro Staging 升级最新版本的 Image Bin + Discuss Kit + Pages Kit
- [ ] 能正常显示文章图片（应用内）
- [ ] 能正常编辑网页图片（Pages Kit）

### 定时任务  @leermao 
- [ ] 本地升级定时任务 Blocklet 的子组件（Discuss Kit、Image Bin），图片能上传到 Discuss Kit

### Vote @donotlb 
- [ ] 本地升级 Vote 的 Comment 组件能正常上传图片

**Comment by FireTable** [comment]
bugbash 前需要做的内容
- [ ] Image Bin 移除目录问题
- [ ] Image Bin 上传文件逻辑，需要跟 folder tab 挂钩
- [ ] Image Bin 移除目前无用的环境变量

**Comment by skypesky** [comment]
## 背景介绍
最近我们新增了通用上传组件 @blocklet/uploader，且替换了部分 Blocklet 的上传功能
1. Image Bin 替换 uppload 组件，并且支持更好的组合上传功能
2. Pages Kit 替换 uppload 组件， 并且复用 Image Bin 上传功能
3. Discuss Kit 替换 uppload 组件，并且兼容 Image Bin，使其更加统一

目前这些 Blocklet 都已经上传到 test store，需要做一次 bugbash 来保证功能正常，然后发布到正式环境

* 所有遇到的问题，一律提交到 Image Bin issues 中，我来做分拣

## 前置准备

除了 Nate 外
1. 准备一些图片与视频，与实时截图的软件（支持 copy paste 到 uploader）
2. 前往 https://node-dev-1.arcblock.io/admin/blocklets/zNKYnJaQwg8xy2vcAKP1XisnfSzVxBUp7wBK/components 领取 admin passport
3. 从 dashboard 选择需要测试的 blocklet

## 功能测试

### 仿新用户测试 @NateRobinson 
https://launcher.staging.arcblock.io/app/?paymentMethod=1en6L0z8GrIW6mYC
- [ ] 安装新版的 Pages Kit，无法移除 Image Bin
- [ ] 安装新版的 Discuss Kit，会额外安装 Image Bin，且无法移除 Image Bin
- [ ] 新用户安装 Image Bin，未配置 UNSPLASH_KEY 不出现 unsplash 插件
       - https://unsplash.com/developers 可以在这里申请
- [ ] 新用户安装 Image Bin，未组合 AI Kit，不出现 AI 插件

### Image Bin  @leermao  @skypesky 
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/image-bin/admin/images
- [ ] 在 /admin/images 点击右上角触发图片上传 dialog
- [ ] 选择多张图片（包括单张）进行上传
- [ ] 使用远程图片上传（URL、Unsplash）
- [ ] 使用 AI 生成图片
- [ ] 拖拽文件到组件 dialog 进行上传
- [ ] 重复文件上传，速度会非常快
- [ ] 选择视频进行上传
- [ ] 在白名单范围外的文件无法上传
      ![image](https://github.com/blocklet/image-bin/assets/24667209/806f8782-4952-492a-99fd-68e03e1b762b)
- [ ] 超过上传大小限制: 30MB 的无法上传
      ![image](https://github.com/blocklet/image-bin/assets/24667209/d6c366ce-bf9f-4c5a-afd3-df676fddf175)
- [ ] 在 Image Bin 上传的图片，可以进行删除
- [ ] 竖排长图 hover 鼠标会进行图片滚动预览
- [ ] 切换顶部的 Tab 来筛选不同 Blocklet 上传的图片，其它 Blocklet 的图片无法删除


### Pages Kit @leermao @donotlb
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/admin/maker
- [ ] 选择单张图片进行上传，无法选择多张
- [ ] 选择视频进行上传
- [ ] 拖拽文件到组件 dialog 进行上传
- [ ] 使用 AI 生成图片
- [ ] 上传的内容可以超过 30MB 的限制大小
- [ ] 上传的内容可以在 Image Bin 查到
- [ ] 使用 Uploaded 选择已经上传的图片


### Discuss Kit @donotlb @skypesky 
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/did-comments/?locale=zh
- [ ] editor 输入 /image ，可以打开 uploader
- [ ] uploader 中可以选择多张图片上传
- [ ] uploader 中使用 AI 生成图片
- [ ] 用远程图片上传（URL、Unsplash）
- [ ] editor 拖拽多张图片触发静默上传
- [ ] 上传的内容可以超过 30MB 的限制大小
- [ ] 上传的内容可以在 Image Bin 查到
- [ ] 使用 Uploaded 选择已经上传的图片
- [ ] 在 Blog 中（/blog），封面图只能上传一张图片


### Aistro @NateRobinson 
- [ ] Aistro Staging 升级最新版本的 Image Bin + Discuss Kit + Pages Kit
- [ ] 能正常显示文章图片（应用内）
- [ ] 能正常编辑网页图片（Pages Kit）



### 定时任务  @leermao 
- [ ] 本地升级定时任务 Blocklet 的子组件（Discuss Kit、Image Bin），图片能上传到 Discuss Kit


### Vote @donotlb 
- [ ] 本地升级 Vote 的 Comment 组件能正常上传图片

**Comment by donotlb** [comment]
### Pages Kit @leermao @donotlb
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/admin/maker
- [ ] 选择单张图片进行上传，无法选择多张
- [ ] 选择视频进行上传
- [ ] 拖拽文件到组件 dialog 进行上传
- [ ] 使用 AI 生成图片
- [ ] 上传的内容可以超过 30MB 的限制大小
- [ ] 上传的内容可以在 Image Bin 查到
- [ ] 使用 Uploaded 选择已经上传的图片


### Discuss Kit @donotlb @skypesky 
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/did-comments/?locale=zh
- [ ] editor 输入 /image ，可以打开 uploader
- [ ] uploader 中可以选择多张图片上传
- [ ] uploader 中使用 AI 生成图片
- [ ] 用远程图片上传（URL、Unsplash）
- [ ] editor 拖拽多张图片触发静默上传
- [ ] 上传的内容可以超过 30MB 的限制大小
- [ ] 上传的内容可以在 Image Bin 查到
- [ ] 使用 Uploaded 选择已经上传的图片
- [ ] 在 Blog 中（/blog），封面图只能上传一张图片

### Vote @donotlb 
- [ ] 本地升级 Vote 的 Comment 组件能正常上传图片

**Comment by leermao** [comment]
## 背景介绍
最近我们新增了通用上传组件 @blocklet/uploader，且替换了部分 Blocklet 的上传功能
1. Image Bin 替换 uppload 组件，并且支持更好的组合上传功能
2. Pages Kit 替换 uppload 组件， 并且复用 Image Bin 上传功能
3. Discuss Kit 替换 uppload 组件，并且兼容 Image Bin，使其更加统一

目前这些 Blocklet 都已经上传到 test store，需要做一次 bugbash 来保证功能正常，然后发布到正式环境

* 所有遇到的问题，一律提交到 Image Bin issues 中，我来做分拣

## 前置准备

除了 Nate 外
1. 准备一些图片与视频，与实时截图的软件（支持 copy paste 到 uploader）
2. 前往 https://node-dev-1.arcblock.io/admin/blocklets/zNKYnJaQwg8xy2vcAKP1XisnfSzVxBUp7wBK/components 领取 admin passport
3. 从 dashboard 选择需要测试的 blocklet

## 功能测试

### 仿新用户测试 @NateRobinson 
https://launcher.staging.arcblock.io/app/?paymentMethod=1en6L0z8GrIW6mYC
- [ ] 安装新版的 Pages Kit，无法移除 Image Bin
- [ ] 安装新版的 Discuss Kit，会额外安装 Image Bin，且无法移除 Image Bin
- [ ] 新用户安装 Image Bin，未配置 UNSPLASH_KEY 不出现 unsplash 插件
       - https://unsplash.com/developers 可以在这里申请
- [ ] 新用户安装 Image Bin，未组合 AI Kit，不出现 AI 插件

### Image Bin  @leermao  @skypesky 
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/image-bin/admin/images
- [ ] 在 /admin/images 点击右上角触发图片上传 dialog
- [ ] 选择多张图片（包括单张）进行上传
- [ ] 使用远程图片上传（URL、Unsplash）
- [ ] 使用 AI 生成图片
- [ ] 拖拽文件到组件 dialog 进行上传
- [ ] 重复文件上传，速度会非常快
- [ ] 选择视频进行上传
- [ ] 在白名单范围外的文件无法上传
      ![image](https://github.com/blocklet/image-bin/assets/24667209/806f8782-4952-492a-99fd-68e03e1b762b)
- [ ] 超过上传大小限制: 30MB 的无法上传
      ![image](https://github.com/blocklet/image-bin/assets/24667209/d6c366ce-bf9f-4c5a-afd3-df676fddf175)
- [ ] 在 Image Bin 上传的图片，可以进行删除
- [ ] 竖排长图 hover 鼠标会进行图片滚动预览
- [ ] 切换顶部的 Tab 来筛选不同 Blocklet 上传的图片，其它 Blocklet 的图片无法删除


### Pages Kit @leermao @donotlb
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/admin/maker
- [ ] 选择单张图片进行上传，无法选择多张
- [ ] 选择视频进行上传
- [ ] 拖拽文件到组件 dialog 进行上传
- [ ] 使用 AI 生成图片
- [ ] 上传的内容可以超过 30MB 的限制大小
- [ ] 上传的内容可以在 Image Bin 查到
- [ ] 使用 Uploaded 选择已经上传的图片


### Discuss Kit @donotlb @skypesky 
https://bbqarpft2b66s4usqfmfb5bsw6sfclz2mjzsdolz4vy.did.abtnet.io/did-comments/?locale=zh
- [ ] editor 输入 /image ，可以打开 uploader
- [ ] uploader 中可以选择多张图片上传
- [ ] uploader 中使用 AI 生成图片
- [ ] 用远程图片上传（URL、Unsplash）
- [ ] editor 拖拽多张图片触发静默上传
- [ ] 上传的内容可以超过 30MB 的限制大小
- [ ] 上传的内容可以在 Image Bin 查到
- [ ] 使用 Uploaded 选择已经上传的图片
- [ ] 在 Blog 中（/blog），封面图只能上传一张图片


### Aistro @NateRobinson 
- [ ] Aistro Staging 升级最新版本的 Image Bin + Discuss Kit + Pages Kit
- [ ] 能正常显示文章图片（应用内）
- [ ] 能正常编辑网页图片（Pages Kit）



### 定时任务  @leermao 
- [ ] 本地升级定时任务 Blocklet 的子组件（Discuss Kit、Image Bin），图片能上传到 Discuss Kit


### Vote @donotlb 
- [ ] 本地升级 Vote 的 Comment 组件能正常上传图片

**Comment by NateRobinson** [comment]
### 仿新用户测试 @NateRobinson 
https://launcher.staging.arcblock.io/app/?paymentMethod=1en6L0z8GrIW6mYC
- [ ] 安装新版的 Pages Kit，无法移除 Image Bin
- [ ] 安装新版的 Discuss Kit，会额外安装 Image Bin，且无法移除 Image Bin
- [ ] 新用户安装 Image Bin，未配置 UNSPLASH_KEY 不出现 unsplash 插件
       - https://unsplash.com/developers 可以在这里申请
- [ ] 新用户安装 Image Bin，未组合 AI Kit，不出现 AI 插件


### Aistro @NateRobinson 
- [ ] Aistro Staging 升级最新版本的 Image Bin + Discuss Kit + Pages Kit
- [ ] 能正常显示文章图片（应用内）
- [ ] 能正常编辑网页图片（Pages Kit）

**Comment by FireTable** [comment]
- [ ] 升级 Marketplace
- [ ] 升级 Vote

**Comment by FireTable** [comment]
已完成，遗留的 2 个 issue 后续处理
